### ISSUE TITLE
The terraform-provider-vmworkstation_v1.0.3 plugin crashed

### ISSUE THREAD

**Issue by fsamv** [elsudano/terraform-provider-vmworkstation#11]
fsvadm@samdebsrv01:~/home-projects/01_gitlab/terraform$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vmworkstation_vm.test_machine will be created
  + resource "vmworkstation_vm" "test_machine" {
      + denomination = "gitlab01"
      + description  = "Vm for gitlab service"
      + id           = (known after apply)
      + memory       = 512
      + path         = "C:\\Users\\fsvadm\\Documents\\Virtual Machines\\gitlab01"
      + processors   = 1
      + sourceid     = "D0VLCTN1U2IO530BQBAVG15S8UVB0FGF"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + vmws_frontend_id = (known after apply)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vmworkstation_vm.test_machine: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with vmworkstation_vm.test_machine,
│   on main.tf line 1, in resource "vmworkstation_vm" "test_machine":
│    1: resource "vmworkstation_vm" "test_machine" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-vmworkstation_v1.0.3 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc07494]

goroutine 28 [running]:
github.com/elsudano/terraform-provider-vmworkstation/vmworkstation.resourceVMWSVmCreate(0xd177e0, {0xdc9280, 0xc00009be40})
        /home/usuario/go/src/github.com/elsudano/terraform-provider-vmworkstation/vmworkstation/resource_vmworkstation_vm.go:82 +0x414
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0003fe0a0, 0xc000225ea0, 0xc00006eaa0, {0xdc9280, 0xc00009be40})
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:320 +0x438
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0000ec580, 0xc000297a68, 0xe1d3f7, 0xf)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000f180, {0xc000101c70, 0x588226}, 0xc000101c70)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xde7800, 0xc00000f180}, {0xfe99f0, 0xc0002a01b0}, 0xc000252240, 0x0)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00057e380, {0xff8d78, 0xc0000faa80}, 0xc000546b00, 0xc000014750, 0x15de9a0, 0x0)
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc00057e380, {0xff8d78, 0xc0000faa80}, 0xc000546b00, 0x0)
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-vmworkstation_v1.0.3 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

fsvadm@samdebsrv01:~/home-projects/01_gitlab/terraform$

**Comment by ct-sce** [comment]
Hello, I didn't try on windows, but with linux, seems the path need to be the full path to the vmx file.

In my case the source vm was in the folder `/home/ct-sce/vmware`( base folder, full path to vmx: `/home/ct-sce/vmware/vagrant-generic-ubuntu-2004/generic-ubuntu2004-vmware.vmx`) and the target vm denomination is consul.
So full path to target vm vmx is `/home/ct-sce/vmware/consul/consul.vmx`

path seems to be like "<source vm base path>/<target vm denomination>/<target vm denomination>.vmx"
or maybe "<default vm>/<target vm denomination>/<target vm denomination>.vmx"

I agree, i did find the solution by looking at the provider, run it with debug enabled and manually test with the API
Like you i though the path would be a folder were the target vm would have been stored in but not.
The deploy on a vm is done in 2 steps, copy from the source vm and then register.
Only register step is using the path.

I wish it will help

regards

**Comment by ct-sce** [comment]
I think it would have been better if path was just a base path, base path as destination folder for the copied vm
and the provider should then do the job of "<base path>/<target vm denomination>/<target vm denomination>.vmx"
ping @elsudano what do you think about it ? I don't know if it possible with the api but i think it's more logic from a "user" perspective

**Comment by alshayed** [comment]
I've run into basically the same error on Windows. The thing that confuses me is that the API documentation (see https://developer.vmware.com/apis/412/vmware-workstation-pro-api) doesn't really seem to let you tell it what to do for the path. It looks like it's something you can get back with a GET /api/vms/{id} though.

**Comment by elsudano** [comment]
This is the problem, that you can see in the API, we haven't a way to copy the machine from the API, we have just a way to check which is the path of the machine.

For that I have to read first where is the place of the instance and then copy at the new place, read the new path and register in the VM workstation.

I have open a issue in the VMware bug panel to try resolve this issues, but for the moment they don't answer me.

I'm waiting for their answer about that

**Comment by alshayed** [comment]
When you say you want to "register" the new vm what do you mean by that? Are you trying to duplicate the parent VM yourself and then add it to VMware Workstation?

**Comment by alshayed** [comment]
The API lets you clone a VM to a new VM pretty easily. Here's the steps:

1. Manually create your base/template vm that will be used to clone new copies
2. HTTP GET /api/vms and find the ID of the template, apparently you have to select by path there
3. HTTP POST to /api/vms (payload = {"name":"new_vm_name","parentId":"___parent_vm_id___"} and it will return the new vm id)
4. optionally change the cpu & memory via API
5. HTTP PUT to /api/vms/___vm_id___/power (payload = "on" with no quotes)

I think the real problem is I don't know how to get the IP address of the new vm so I can ssh into it and control it. The HTTP GET /api/vmnets/xxx/mactoip doesn't seem to be returning any data for some reason and it's not coming through on the /api/vms either. Maybe if you get the path for the new vm and then look through the files in the vm folder it's there somewhere, presumably only after you start it.

**Comment by alshayed** [comment]
From a cursory look it appears if the vmnet api doesn't return ip information then you have to search the vmware.log file for IP= lines to get ip addresses.

**Comment by elsudano** [comment]
I will to try answer by parts

First: if you work with workstation, I suppose that you want clone the parent VM and then that the instance appear in the VM workstation UI, then you need to clone the VM and then register the new VM in the UI of VM workstation by API.

Please try that for understand the main problem.

Second, if you use the debug setting in the provider you will be able to check that this part working properly to clone the VM but fail when the provider try to register the VM in the UI.

And the last one, as you said if you need to change some settings in the new VM you can't do that by API, for that I'm trying to change the settings by the VMX new file with the a VMX library within in the provider code

I hope that I explain correctly which is the main issue in this case

**Comment by alshayed** [comment]
Ah, I can see we have a fundamentally different perspective. Your top priority is having the newly generated VM show up in the GUI. 

Personally, I don't really care about the GUI. I mean it's easy enough to add the new VM to it manually if needed. But if you take the headline from the Terraform website "Automate Infrastructure on Any Cloud", my hope for this plugin was to use it as a lab & experimentation environment. Specifically I was hoping to automate creation of a Kubernetes cluster on my PC inside VMware Workstation the same way I might with a cloud provider or vSphere. AFAIK the only GUI interface for Kubernetes is through your web browser so directly interacting with the VM inside VMware Workstation isn't really something that particularly matters.

**Comment by cgomez1** [comment]
Hello guys,

I have the same issue and I don't know how to solve it.

Below you can see trace logs but I'm not sure at all if is it something with the DATA that I define in VARS or an internal provider issue. Please, could you take a look?

BTW, I tried directly to the API and it works fine.

curl 'http://127.0.0.1:8697/api/vms' -X POST --header 'Content-Type: application/vnd.vmware.vmw.rest-v1+json' --header 'Accept: application/vnd.vmware.vmw.rest-v1+json' --header 'Authorization: Basic dm13YXJlOkhqZXkhNjctMTFB' -d @- <<REQUEST_BODY 
{
   "name": "new_vm_name",
   "parentId": "LIRB9IPAMC6VASAM8L0RCIQEUERI9EHG"
}
REQUEST_BODY

You can details in the log blow:

vmworkstation_vm.test_machine: Creating...
2022-11-29T12:53:08.177-0500 [INFO]  Starting apply for vmworkstation_vm.test_machine
2022-11-29T12:53:08.177-0500 [DEBUG] vmworkstation_vm.test_machine: applying the planned Create change
2022-11-29T12:53:08.177-0500 [TRACE] GRPCProvider: ApplyResourceChange
2022-11-29T12:53:08.181-0500 [TRACE] provider.stdio: received data: channel=STDERR len=1024
2022-11-29T12:53:08.181-0500 [WARN]  unexpected data: registry.terraform.io/elsudano/vmworkstation:stderr="2022/11/29 12:53:08 [VMWS] Fi: resource_vmworkstation_vm.go Fu: resourceVMWSVmCreate Ob:
2022/11/29 12:53:08      sourceid: "LIRB9IPAMC6VASAM8L0RCIQEUERI9EHG"
2022/11/29 12:53:08      denomination: "NewVMFromTerraform"
2022/11/29 12:53:08      description: "New VM From Terraform"
2022/11/29 12:53:08      path: "/home/cgomez/Vmware/NewVMFromTerraform"
2022/11/29 12:53:08      processors: 2
2022/11/29 12:53:08      memory: 4096
2022/11/29 12:53:08 [WSAPICLI] Fi: wsapivm.go Fu: CreateVM Obj:Request Body "{\"name\":\"NewVMFromTerraform\",\"parentId\":\"LIRB9IPAMC6VASAM8L0RCIQEUERI9EHG\"}\n"
2022/11/29 12:53:08 [WSAPICLI] Fi: wsapiclient.go Fu: requestPath Obj:"https://localhost:8697/api/vms"
2022/11/29 12:53:08 [WSAPICLI] Fi: wsapiclient.go Fu: httpRequest Obj:buffer "{\"name\":\"NewVMFromTerraform\",\"parentId\":\"LIRB9IPAMC6VASAM8L0RCIQEUERI9EHG\"}\n"
2022/11/29 12:53:08 [WSAPICLI] Fi: wsapiclient.go Fu: httpRequest Obj: Rrequest before that run &http.Request{Method:"POST", URL:(*url.URL)(0xc0004a6870), Proto:"HTTP/1.1", ProtoMa"
2022-11-29T12:53:08.181-0500 [TRACE] provider.stdio: waiting for stdio data
2022-11-29T12:53:08.181-0500 [TRACE] provider.stdio: received data: channel=STDERR len=641
2022-11-29T12:53:08.181-0500 [WARN]  unexpected data: registry.terraform.io/elsudano/vmworkstation:stderr="jor:1, ProtoMinor:1, Header:http.Header{"Authorization":[]string{"Basic dm13YXJlOkhqZXkhNjctMTFB"}, "Content-Type":[]string{"application/vnd.vmware.vmw.rest-v1+json"}}, Body:io.nopCloser{Reader:(*bytes.Buffer)(0xc000194bd0)}, GetBody:(func() (io.ReadCloser, error))(0x699060), ContentLength:76, TransferEncoding:[]string(nil), Close:false, Host:"localhost:8697", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"", RequestURI:"", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.emptyCtx)(0xc000034150)}"
2022-11-29T12:53:08.181-0500 [TRACE] provider.stdio: waiting for stdio data
2022-11-29T12:53:08.184-0500 [DEBUG] provider.terraform-provider-vmworkstation_v1.0.3: panic: runtime error: invalid memory address or nil pointer dereference
2022-11-29T12:53:08.184-0500 [DEBUG] provider.terraform-provider-vmworkstation_v1.0.3: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc07494]

Thanks in advance.

**Comment by elsudano** [comment]
> Ah, I can see we have a fundamentally different perspective. Your top priority is having the newly generated VM show up in the GUI.
> 
> Personally, I don't really care about the GUI. I mean it's easy enough to add the new VM to it manually if needed. But if you take the headline from the Terraform website "Automate Infrastructure on Any Cloud", my hope for this plugin was to use it as a lab & experimentation environment. Specifically I was hoping to automate creation of a Kubernetes cluster on my PC inside VMware Workstation the same way I might with a cloud provider or vSphere. AFAIK the only GUI interface for Kubernetes is through your web browser so directly interacting with the VM inside VMware Workstation isn't really something that particularly matters.

Yep, you right, and I understood perfectly, buy my point is that if you use Terraform for a LAB is necessary complete all the process, because the people starts with Terraform is a little bit confuse when the instance is created but not appear in the GUI.

In my mind this step is the first step to adopt the Terraform, if you use Terraform in a LAB and work fine, you can jump at the cloud or Kubernetes.

Anyway, thanks for your feedback and for test the provider.

Maybe this holidays I can continue with the develop.

**Comment by elsudano** [comment]
> Hello guys,
> 
> I have the same issue and I don't know how to solve it.
> 
> Below you can see trace logs but I'm not sure at all if is it something with the DATA that I define in VARS or an internal provider issue. Please, could you take a look?
> 
> BTW, I tried directly to the API and it works fine.
> 
> curl 'http://127.0.0.1:8697/api/vms' -X POST --header 'Content-Type: application/vnd.vmware.vmw.rest-v1+json' --header 'Accept: application/vnd.vmware.vmw.rest-v1+json' --header 'Authorization: Basic dm13YXJlOkhqZXkhNjctMTFB' -d @- <<REQUEST_BODY { "name": "new_vm_name", "parentId": "LIRB9IPAMC6VASAM8L0RCIQEUERI9EHG" } REQUEST_BODY
> 
> You can details in the log blow:
> 
> vmworkstation_vm.test_machine: Creating... 2022-11-29T12:53:08.177-0500 [INFO] Starting apply for vmworkstation_vm.test_machine 2022-11-29T12:53:08.177-0500 [DEBUG] vmworkstation_vm.test_machine: applying the planned Create change 2022-11-29T12:53:08.177-0500 [TRACE] GRPCProvider: ApplyResourceChange 2022-11-29T12:53:08.181-0500 [TRACE] provider.stdio: received data: channel=STDERR len=1024 2022-11-29T12:53:08.181-0500 [WARN] unexpected data: registry.terraform.io/elsudano/vmworkstation:stderr="2022/11/29 12:53:08 [VMWS] Fi: resource_vmworkstation_vm.go Fu: resourceVMWSVmCreate Ob: 2022/11/29 12:53:08 sourceid: "LIRB9IPAMC6VASAM8L0RCIQEUERI9EHG" 2022/11/29 12:53:08 denomination: "NewVMFromTerraform" 2022/11/29 12:53:08 description: "New VM From Terraform" 2022/11/29 12:53:08 path: "/home/cgomez/Vmware/NewVMFromTerraform" 2022/11/29 12:53:08 processors: 2 2022/11/29 12:53:08 memory: 4096 2022/11/29 12:53:08 [WSAPICLI] Fi: wsapivm.go Fu: CreateVM Obj:Request Body "{"name":"NewVMFromTerraform","parentId":"LIRB9IPAMC6VASAM8L0RCIQEUERI9EHG"}\n" 2022/11/29 12:53:08 [WSAPICLI] Fi: wsapiclient.go Fu: requestPath Obj:"https://localhost:8697/api/vms" 2022/11/29 12:53:08 [WSAPICLI] Fi: wsapiclient.go Fu: httpRequest Obj:buffer "{"name":"NewVMFromTerraform","parentId":"LIRB9IPAMC6VASAM8L0RCIQEUERI9EHG"}\n" 2022/11/29 12:53:08 [WSAPICLI] Fi: wsapiclient.go Fu: httpRequest Obj: Rrequest before that run &http.Request{Method:"POST", URL:(*url.URL)(0xc0004a6870), Proto:"HTTP/1.1", ProtoMa" 2022-11-29T12:53:08.181-0500 [TRACE] provider.stdio: waiting for stdio data 2022-11-29T12:53:08.181-0500 [TRACE] provider.stdio: received data: channel=STDERR len=641 2022-11-29T12:53:08.181-0500 [WARN] unexpected data: registry.terraform.io/elsudano/vmworkstation:stderr="jor:1, ProtoMinor:1, Header:http.Header{"Authorization":[]string{"Basic dm13YXJlOkhqZXkhNjctMTFB"}, "Content-Type":[]string{"application/vnd.vmware.vmw.rest-v1+json"}}, Body:io.nopCloser{Reader:(*bytes.Buffer)(0xc000194bd0)}, GetBody:(func() (io.ReadCloser, error))(0x699060), ContentLength:76, TransferEncoding:[]string(nil), Close:false, Host:"localhost:8697", Form:url.Values(nil), PostForm:url.Values(nil), MultipartForm:(*multipart.Form)(nil), Trailer:http.Header(nil), RemoteAddr:"", RequestURI:"", TLS:(*tls.ConnectionState)(nil), Cancel:(<-chan struct {})(nil), Response:(*http.Response)(nil), ctx:(*context.emptyCtx)(0xc000034150)}" 2022-11-29T12:53:08.181-0500 [TRACE] provider.stdio: waiting for stdio data 2022-11-29T12:53:08.184-0500 [DEBUG] provider.terraform-provider-vmworkstation_v1.0.3: panic: runtime error: invalid memory address or nil pointer dereference 2022-11-29T12:53:08.184-0500 [DEBUG] provider.terraform-provider-vmworkstation_v1.0.3: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc07494]
> 
> Thanks in advance.

Maybe the error is that you use a HTTP://127.0.0.1 in your request and use HTTPS://localhost in your configuration of provider 

If you check the debug trace, you can see the difference

Anyway, as I said in the thread, I need to review why the API of VMWorkstation not give me the correct data when I ask it.

**Comment by AltheronCrust** [comment]
Aloha. Unfortunately facing the same issue.  

`Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # vmworkstation_vm.test_machine will be created
  + resource "vmworkstation_vm" "test_machine" {
      + denomination = "NewInstance"
      + description  = "Some description"
      + id           = (known after apply)
      + memory       = 512
      + path         = "C:\\Users\\adamg\\OneDrive\\Dokumenty\\Virtual Machines\\test_machine.vmx"
      + processors   = 1
      + sourceid     = "56 4d 99 44 f8 10 ec cf-fb 7c 16 30 3b 4b 55 b1"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + vmws_frontend_id = (known after apply)

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vmworkstation_vm.test_machine: Creating...
╷
│ Error: Plugin did not respond
│
│   with vmworkstation_vm.test_machine,
│   on main.tf line 19, in resource "vmworkstation_vm" "test_machine":
│   19: resource "vmworkstation_vm" "test_machine" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The
│ plugin logs may contain more details.
╵

Stack trace from the terraform-provider-vmworkstation_v1.0.3.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x157d714]

goroutine 27 [running]:
github.com/elsudano/terraform-provider-vmworkstation/vmworkstation.resourceVMWSVmCreate(0x168e040, {0x173fb60, 0xc00034a380})
        /home/usuario/go/src/github.com/elsudano/terraform-provider-vmworkstation/vmworkstation/resource_vmworkstation_vm.go:82 +0x414
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00048c0a0, 0xc00008bae0, 0xc000696480, {0x173fb60, 0xc00034a380})
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:320 +0x438
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000042500, 0xc00064da68, 0x1793e8e, 0xf)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000006f28, {0xc00019e620, 0xf081a6}, 0xc00019e620)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:895 +0x7c5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x175e3c0, 0xc000006f28}, {0x1963bd0, 0xc0004949c0}, 0xc00068db00, 0x0)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3305 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000552700, {0x1973978, 0xc00019aa80}, 0xc000168400, 0xc0001939e0, 0x1f5d800, 0x0)
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc000552700, {0x1973978, 0xc00019aa80}, 0xc000168400, 0x0)
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x294

Error: The terraform-provider-vmworkstation_v1.0.3.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
`


And im wondering, if its not directly go related issue, had similar case where err != nil - havent been checked correctly despite of fact using defer func.

**Comment by chrodrigues** [comment]
The same issue here:

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vmworkstation_vm.test_machine will be created
  + resource "vmworkstation_vm" "test_machine" {
      + denomination = "home-lab"
      + description  = "instance-test"
      + id           = (known after apply)
      + memory       = 4
      + path         = "C:\\VMware"
      + processors   = 1
      + sourceid     = "56 4d dd a8 1b 18 f6 b7-ad e6 11 25 7a 91 75 ee"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vmworkstation_vm.test_machine: Creating...
╷
│ Error: Request cancelled
│
│   with vmworkstation_vm.test_machine,
│   on main.tf line 11, in resource "vmworkstation_vm" "test_machine":
│   11: resource "vmworkstation_vm" "test_machine" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-vmworkstation_v0.2.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99d6d3]

goroutine 82 [running]:
github.com/elsudano/terraform-provider-vmworkstation/vmworkstation.resourceVMWSVmCreate(0xc000181050, 0xc69220, 0xc0000a09c0, 0x2, 0x121cfc0)
        /home/usuario/go/src/github.com/elsudano/terraform-provider-vmworkstation/vmworkstation/resource_vmworkstation_vm.go:82 +0x5b3
github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0002ae000, 0xc000247030, 0xc00055a720, 0xc69220, 0xc0000a09c0, 0x1, 0x0, 0x0)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform@v0.13.3/helper/schema/resource.go:308 +0x3b8
github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0002ae180, 0xc00056fa08, 0xc000247030, 0xc00055a720, 0xc00013e540, 0xdbc490, 0xc00013e540)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform@v0.13.3/helper/schema/provider.go:297 +0x99
github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000286020, 0xdbba80, 0xc0003038c0, 0xc000246ee0, 0xc000286020, 0xc0003038c0, 0xc00008eb80)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform@v0.13.3/helper/plugin/grpc_provider.go:923 +0x8e5
github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xc8d0c0, 0xc000286020, 0xdbba80, 0xc0003038c0, 0xc000304960, 0x0, 0xdbba80, 0xc0003038c0, 0xc000016300, 0x166)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform@v0.13.3/internal/tfplugin5/tfplugin5.pb.go:3303 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002b4900, 0xdc2778, 0xc0002b5380, 0xc0002ad600, 0xc000282fc0, 0x11df680, 0x0, 0x0, 0x0)
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc0002b4900, 0xdc2778, 0xc0002b5380, 0xc0002ad600, 0x0)
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00013a450, 0xc0002b4900, 0xdc2778, 0xc0002b5380, 0xc0002ad600)
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa5

Error: The terraform-provider-vmworkstation_v0.2.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

 charlin@alienware   ~/thingslikethat/Terraform/vmware-workstation     main                                               1 ↵  661  14:27:14   
 charlin@alienware   ~/thingslikethat/Terraform/vmware-workstation     main    terraform apply                    SIGINT(2) ↵  661  14:27:27   

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vmworkstation_vm.test_machine will be created
  + resource "vmworkstation_vm" "test_machine" {
      + denomination = "home-lab"
      + description  = "instance-test"
      + id           = (known after apply)
      + memory       = 4
      + path         = "C:\\VMware"
      + processors   = 1
      + sourceid     = "56 4d dd a8 1b 18 f6 b7-ad e6 11 25 7a 91 75 ee"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

vmworkstation_vm.test_machine: Creating...
╷
│ Error: Plugin did not respond
│
│   with vmworkstation_vm.test_machine,
│   on main.tf line 11, in resource "vmworkstation_vm" "test_machine":
│   11: resource "vmworkstation_vm" "test_machine" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details. 
╵

Stack trace from the terraform-provider-vmworkstation_v0.2.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x99d6d3]

goroutine 48 [running]:
github.com/elsudano/terraform-provider-vmworkstation/vmworkstation.resourceVMWSVmCreate(0xc000184cf0, 0xc69220, 0xc00028c880, 0x2, 0x121cfc0)
        /home/usuario/go/src/github.com/elsudano/terraform-provider-vmworkstation/vmworkstation/resource_vmworkstation_vm.go:82 +0x5b3
github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc0002ac000, 0xc000187810, 0xc000510600, 0xc69220, 0xc00028c880, 0x1, 0x0, 0x0)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform@v0.13.3/helper/schema/resource.go:308 +0x3b8
github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc0002ac180, 0xc000423a08, 0xc000187810, 0xc000510600, 0xc000010550, 0xdbc490, 0xc000010550)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform@v0.13.3/helper/schema/provider.go:297 +0x99
github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000288028, 0xdbba80, 0xc000241dd0, 0xc0001876c0, 0xc000288028, 0xc000241dd0, 0xc00055bb80)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform@v0.13.3/helper/plugin/grpc_provider.go:923 +0x8e5
github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xc8d0c0, 0xc000288028, 0xdbba80, 0xc000241dd0, 0xc000281440, 0x0, 0xdbba80, 0xc000241dd0, 0xc00052a300, 0x166)
        /home/usuario/go/pkg/mod/github.com/hashicorp/terraform@v0.13.3/internal/tfplugin5/tfplugin5.pb.go:3303 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000103380, 0xdc2778, 0xc000502480, 0xc000419a00, 0xc0001126f0, 0x11df680, 0x0, 0x0, 0x0)
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000103380, 0xdc2778, 0xc000502480, 0xc000419a00, 0x0)
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000110180, 0xc000103380, 0xdc2778, 0xc000502480, 0xc000419a00)
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/usuario/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa5

Error: The terraform-provider-vmworkstation_v0.2.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue

**Comment by VictorNuzhdin** [comment]
This is very sad that the provider’s developer still hasn’t fixed it,
but this provider is still in the Hashicorp documentation..
Provider still doesnt work on Windows
(Windows 10 v22H2, Terraform v1.7.3, elsudano/vmworkstation v1.0.3)

**Comment by elsudano** [comment]
Hi guys, after review the API of the VmWare Workstation, they had solved some issues that they had in the API calls, so this weekend I published another version 1.0.4

https://registry.terraform.io/providers/elsudano/vmworkstation/latest

If you want to take a look in order to see if I had be able to solve the issue, up to you.

All the feedback will be welcome
